### ISSUE TITLE
Trying to figure our which tiles to load

### ISSUE THREAD

**Issue by matthiasfeist** [blacha/cogeotiff#1288]
Hi.

I'm currently experimenting a bit with this library. I want to do an analysis of certain coordinates in a geoTiff. However, I am struggling with calculating the right geoTiff tile for a given coordinate.

I was wondering if it would be handy to have a utility function in your library where you can get the tile number that contains a given lat/long pair?

**Comment by blacha** [comment]
Hi @matthiasfeist, sorry I missed this issue.

Due to the many ways that geotiffs can handle coordinates, I have chose to leave most of that logic out of this library.

Generally a tiff will store its coordinates inside the root image `tiff.images[0].bbox` this will be in the coordinate system of the tiff, `tiff.images[0].epsg` eg "EPSG:3857" so then you would need to project the bbox into a `EPSG:4326` lat,lng bounding box.

We run a aerial imagery service using this library, when we create the tiffs of our aerial imagery we specifically make them to be easy to be consumed.

this function here https://github.com/linz/basemaps/blob/master/packages/tiler/src/tiler.ts#L89 takes a collection of tiffs and creates a list of regions that are needed from each tiff to create a output slippy map tile, it does not  support re-projecting the tiff though.
