### ISSUE TITLE
Help wanted? & a few questions

### ISSUE THREAD

**Issue by rowanwins** [blacha/cogeotiff#271]
Hi @blacha

It looks like you're doing some really interesting work in this repo. I had a few questions around where it's headed and whether you need any help getting there...

1. So it looks like you are creating a capability similar to [geotiff.js](https://github.com/geotiffjs/geotiff.js/). Do you have a roadmap or any points of difference?
2. Are you run into any issues with the node vs browser compatibility
3. Are you in need of any help? Creating doco or perhaps more fully fleshed out plugins for front-end libs etc?
4. Have you done any benchmarks against geotiff.js around performance?

Cheers
Rowan

**Comment by blacha** [comment]
Hi @rowanwins 

I primary reason this repo was built was to learn more about the new GDAL 3.1 COG optimizations. It has turned out it provides very fast access to tiles from these COGs and so I have started using it in a few other places.

1. geotiff.js to me seems more around reading and decoding the images so math can be applied to them and rendered. Due to the decoding process it means it is very slow (100s of ms) to actually get the tile.
 I have no plans of implementing Jpeg/webp decoders, the raw image data can be given to another service to decode, I have currently used both libvips (sharp) and Canvas to do the decoding of the imagery tiles.

2. I am unaware of any browser or node issues with this repo,  I currently run this in AWS Lambda, and in the browser without issues.

3. I am currently working on a tiling algorithm, that would mean you could plug a COG url (or collection of COGs urls) into something like openlayers and it would render everything correctly in the browser (no server). I have this working in node (using libvips/sharp). If you have ideas for enhancements, let me know.

4. I have only really done adhoc testing when using their website. I have access to a few large (2TB+) cogs that when trying to use the geotiff.js basically crashes the browser, where as this tool generally reads them from local disk in a few ms.

I have another repo I am working on [linz/basemaps](https://github.com/linz/basemaps) which utilizes this to create a basemap layer from a collection of COGs, it has a few utilities and benchmarks inside it.

**Local server** `./test-serve.js <path-to-cogs>`  will spin up a local express server and serve the cogs to the user.
https://github.com/linz/basemaps/blob/master/packages/lambda-xyz/test-serve.js

**Benchmarks**
Runs some read/write benchmarks and tile composing in libvips/sharp
https://github.com/linz/basemaps/blob/master/packages/tiler/src/__test__/tile.benchmark.test.ts

example benchmark https://github.com/linz/basemaps/runs/422152470#step:8:14 where its generally <1ms to initialize and read a tile.

I have been working with a github-action to automatically graph these benchmarks but that is on the back burner atm [blacha/hyperfine-action](https://github.com/blacha/hyperfine-action)

**Comment by rowanwins** [comment]
Very interesting - thanks for the info @blacha
